version: '3.7'
services:

    php-fpm:
        image: ${REGISTRY}/${PHP_FMP_CONTAINER_NAME}:${IMAGE_TAG}
        volumes:
            - .:/app

    php-cli:
        image: ${REGISTRY}/${PHP_CLI_CONTAINER_NAME}:${IMAGE_TAG}
        volumes:
            - .:/app

    nginx:
        image: ${REGISTRY}/${NGINX_CONTAINER_NAME}:${IMAGE_TAG}
        ports:
            - ${APP_WEB_PORT}:80
        volumes:
            - .:/app